Added Ribir & unified punctiuation of descriptions
areweguiyet/areweguiyet pull request #152
Opened 2024-02-25 21:32 UTC by virtualritz

* Added [`Ribir`](https://crates.io/crates/ribir) ([repo](https://github.com/RibirX/Ribir)).
   I didn't add `tags` since there are no written guiderails in the `CONTRIBUTING.md` for what that field should contain. The `tags` used in `ecosystem.toml` on other crates seem to follow no stringent logic. Some pertain to _what_, some to _how_, etc.

* Unified use of punctuation in `description` fields. Some had a terminating period, some didn't.
 
P.S.: It would help if `CONTRIBUTING.md` listed all the fields one should populate, when a crate is not published on `crates.io`. Maybe an example `toml` snippet? :grin:

2024-02-25 23:35 UTC, madsmtm requested changes
Re punctuation: Most crates on crates.io don't use a period, and this is where the `description` field is otherwise taken from. I'd rather not have a period in the data, and instead normalize the data from crates.io when outputting it (but that should be done in a separate PR).

Re tags: You're right that there isn't really any guidelines for these, I wanted to do https://github.com/areweguiyet/areweguiyet/pull/119, but that has kinda stalled.

2024-02-26 12:11 UTC, virtualritz commented
> Re punctuation: Most crates on crates.io don't use a period, and this is where the description field is otherwise taken from. I'd rather not have a period in the data, and instead normalize the data from crates.io when outputting it (but that should be done in a separate PR).

Fair enough. But 'most' means some still do. What's more, `ecosystem.toml` has multi sentence descriptions.
What then? Don't have a period after the last sentence nevertheless?
As an ex typographer/designer, that makes my toenails curl.

The fact that there are no guiderails for the `description` field of a `Cargo.toml` doesn't mean `areweguiyet` can't do better.

If you decide to have a final period in those multi-sentence cases but not for the one sentence descriptions, the style is not stringent. I.e. why I made these changes.

Just saying. 😁

2024-04-18 18:25 UTC, madsmtm commented
I went and normalized the descriptions visually in https://github.com/areweguiyet/areweguiyet/pull/157, please update this PR to not change the `description` fields of the other crates

2025-01-08 15:26 UTC, madsmtm commented
Superseded by https://github.com/areweguiyet/areweguiyet/pull/179

2025-01-08 15:26 UTC, closed without merging